#+TITLE: Experiment UI - Side Menu

* INTRODUCTION
This document describes the side menu of the experiment user
interface.

* PURPOSE OF THE SIDE MENU
The side menu is intended as navigation tool for the user.  It allows
the user to navigate different parts/units of the experiment that are
divided into different pages.  The side menu highlights the current
page to make it easy for the user to track their location in the
experiment.

* FEATURES
The side menu provides the following features:

** Links to all the pages in the experiment
The side menu provies links to all the pages in the experiment. The side menu also has a contributors page where the names and contact infor of SME's and the developers of the experiment is captured. 

The following steps list the process to be followed to add this information. 

Step 1 : Go to the experiment directory, in the respective experiment repository.    

Step 2 : Add the file contributors.md  in the experiment directory.  This file can be found here.  

Step 3 : Remove the first line in the contributors.md. Fill in the required content as per the template provided. If required you may change the presentation template. If needed, you can also add a Credit section to this file. 

Step 4 : Push the changes to the testing branch. You will be able to see the Contributors option on the Side Menu panel (left)  on the repository's github hosted page. 

** Highlights the link to the current page
To facilitate tracking the current page, the side menu highlights the
link to the current page in a different text color.

** Drawers for links to nested units

Ther are three kinds of units: Learning Unit, Task, and Aim.  Out
these units, only Task and Aim units have a page.  Learning units do
not have a page.  This difference is reflected in the side menu as
follows:

- TASK AND AIM :: For Task and Aim units, the side menu provides links
                  to the corresponding pages.

- LEARNING UNIT :: Learning units do have pages associated with them.
                   The side menu has a drawer in place of a link for
                   each learning unit.  The drawer groups all links to
                   the units within the learning unit and the user can
                   open/close the drawer to access the links contained
                   within.
		   
		   If drawer that contains the link to the current
                   page is open by default.
